version: "3.5"

services:

# ----------------------------------------
  # Go service backend
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - 8089:8089
    volumes:
      - .:/go/reunion
      - /go/reunion/ui
    networks:
      - shared
    working_dir: /go/reunion
    restart: on-failure

# ----------------------------------------
  # Vue UI 
  ui:
    build:
      context: ./ui
      dockerfile: ../docker/ui/Dockerfile
    working_dir: /app
    volumes:
      - ./ui:/app
      - /app/node_modules/
    ports:
      - 8088:8088
    networks:
      - shared
    command: bash -c "npm install && npm run dev"

volumes:
  go-modules:
    driver: local

networks:
  shared:
    name: renet

